export const paths = {
  SPLASH: 'Splash',
  ONBOARDING: 'Onboarding',
  AUTHSTACK: 'AuthStack',
  LOGIN: 'Login',
  REGISTER: 'Register',
  HOMESTACK: 'HomeStack',
  HOME: 'Home',
  FAVORITESSTACK: 'FavoritesStack',
  FAVORITES: 'Favorites',
  SETTINGSSTACK: 'SettingsStack',
  SETTINGS: 'Settings',
  BOTTOMNAVIGATION: 'BottomNavigation',
  DETAILS: 'Details',
  VIDEODETAILS: 'VideoDetails',
  ALLITEMS: 'AllItems',
  SEARCH: 'Search',
  DEPOSIT: 'Deposit',
  CATEGORYITEMS: 'CategoryItems',
} as const;
